version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: skillmatch
    ports: ["5442:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgres://dev:dev@db:5432/skillmatch
    ports: ["8000:8000"]
    depends_on: [db]

volumes:
  db-data:
